In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

# Census API Key
from config import api_key
c = Census(api_key)

In [35]:
##Create a function to get the population data by year

def get_pop_data():
    url = f"https://api.census.gov/data/{year}/pep/population?get=STATE,POP&for=state:*"
    response=requests.get(url)
    response.json()
    population_data = response.json()
    population_df = pd.DataFrame(population_data, columns=["State", "Population", "State Code"])
    population_df.drop([0], inplace=True)
    print(url)

In [39]:
year=2015
get_pop_data()
states = []
pop_2015 = []
population_df
for state,pop in population_df[['State','Population']].itertuples(index=False): 
    states.append(state)
    pop_2015.append(pop)

https://api.census.gov/data/2015/pep/population?get=STATE,POP&for=state:*

In [40]:
year=2016
get_pop_data()
states = []
pop_2016 = []
population_df
for state,pop in population_df[['State','Population']].itertuples(index=False): 
    states.append(state)
    pop_2016.append(pop)

https://api.census.gov/data/2016/pep/population?get=STATE,POP&for=state:*

In [41]:
year=2017
get_pop_data()
states = []
pop_2017 = []
population_df
for state,pop in population_df[['State','Population']].itertuples(index=False): 
    states.append(state)
    pop_2017.append(pop)

https://api.census.gov/data/2017/pep/population?get=STATE,POP&for=state:*

In [42]:
year=2018
get_pop_data()
states = []
pop_2018 = []
population_df
for state,pop in population_df[['State','Population']].itertuples(index=False): 
    states.append(state)
    pop_2018.append(pop)

https://api.census.gov/data/2018/pep/population?get=STATE,POP&for=state:*

In [43]:
pop_df = pd.DataFrame({'States': states,
                      "2015": pop_2015,
                      "2016": pop_2016,
                       "2017": pop_2017,
                       "2018": pop_2018})
    
   
pop_df['States']=pop_df["States"].astype(float)
pop_df.dtypes

States    float64
2015       object
2016       object
2017       object
2018       object
dtype: object

In [44]:
filepath="state-geocodes-v2017.csv"
state_codes = pd.read_csv(filepath)
state_codes_df = pd.DataFrame({
    "States": state_codes["State (FIPS)"].astype(float),
    "State Name": state_codes["Name"]
})
state_codes_df.dtypes

States        float64
State Name     object
dtype: object

In [45]:
new_df = pd.merge(pop_df, state_codes_df, how='left', on="States")

new_df

    States      2015      2016      2017      2018            State Name
0      1.0   4858979   4858979   4858979   4858979               Alabama
1      2.0    738432    738432    738432    738432                Alaska
2      4.0   6828065   6828065   6828065   6828065               Arizona
3      5.0   2978204   2978204   2978204   2978204              Arkansas
4      6.0  39144818  39144818  39144818  39144818            California
5      8.0   5456574   5456574   5456574   5456574              Colorado
6      9.0   3590886   3590886   3590886   3590886           Connecticut
7     10.0    945934    945934    945934    945934              Delaware
8     11.0    672228    672228    672228    672228  District of Columbia
9     12.0  20271272  20271272  20271272  20271272               Florida
10    13.0  10214860  10214860  10214860  10214860               Georgia
11    15.0   1431603   1431603   1431603   1431603                Hawaii
12    17.0  12859995  12859995  12859995  12859995              Illinois
13    16.0   1654930   1654930   1654930   1654930                 Idaho
14    18.0   6619680   6619680   6619680   6619680               Indiana
15    29.0   6083672   6083672   6083672   6083672              Missouri
16    28.0   2992333   2992333   2992333   2992333           Mississippi
17    25.0   6794422   6794422   6794422   6794422         Massachusetts
18    27.0   5489594   5489594   5489594   5489594             Minnesota
19    26.0   9922576   9922576   9922576   9922576              Michigan
20    23.0   1329328   1329328   1329328   1329328                 Maine
21    24.0   6006401   6006401   6006401   6006401              Maryland
22    22.0   4670724   4670724   4670724   4670724             Louisiana
23    20.0   2911641   2911641   2911641   2911641                Kansas
24    19.0   3123899   3123899   3123899   3123899                  Iowa
25    21.0   4425092   4425092   4425092   4425092              Kentucky
26    38.0    756927    756927    756927    756927          North Dakota
27    41.0   4028977   4028977   4028977   4028977                Oregon
28    40.0   3911338   3911338   3911338   3911338              Oklahoma
29    42.0  12802503  12802503  12802503  12802503          Pennsylvania
30    39.0  11613423  11613423  11613423  11613423                  Ohio
31    37.0  10042802  10042802  10042802  10042802        North Carolina
32    35.0   2085109   2085109   2085109   2085109            New Mexico
33    30.0   1032949   1032949   1032949   1032949               Montana
34    36.0  19795791  19795791  19795791  19795791              New York
35    32.0   2890845   2890845   2890845   2890845                Nevada
36    31.0   1896190   1896190   1896190   1896190              Nebraska
37    33.0   1330608   1330608   1330608   1330608         New Hampshire
38    34.0   8958013   8958013   8958013   8958013            New Jersey
39    49.0   2995919   2995919   2995919   2995919                  Utah
40    54.0   1844128   1844128   1844128   1844128         West Virginia
41    50.0    626042    626042    626042    626042               Vermont
42    51.0   8382993   8382993   8382993   8382993              Virginia
43    55.0   5771337   5771337   5771337   5771337             Wisconsin
44    53.0   7170351   7170351   7170351   7170351            Washington
45    44.0   1056298   1056298   1056298   1056298          Rhode Island
46    45.0   4896146   4896146   4896146   4896146        South Carolina
47    47.0   6600299   6600299   6600299   6600299             Tennessee
48    48.0  27469114  27469114  27469114  27469114                 Texas
49    46.0    858469    858469    858469    858469          South Dakota
50    56.0    586107    586107    586107    586107               Wyoming
51    72.0   3474182   3474182   3474182   3474182                   NaN

In [54]:
population_df_clean = pd.DataFrame ({
    "State": new_df["State Name"],
    "Population": new_df['2015'],
    "State Code": new_df['States']
})
population_df_clean.to_csv("state_population_data.csv", index=False)
population_df_clean

                   State Population  State Code
0                Alabama    4858979         1.0
1                 Alaska     738432         2.0
2                Arizona    6828065         4.0
3               Arkansas    2978204         5.0
4             California   39144818         6.0
5               Colorado    5456574         8.0
6            Connecticut    3590886         9.0
7               Delaware     945934        10.0
8   District of Columbia     672228        11.0
9                Florida   20271272        12.0
10               Georgia   10214860        13.0
11                Hawaii    1431603        15.0
12              Illinois   12859995        17.0
13                 Idaho    1654930        16.0
14               Indiana    6619680        18.0
15              Missouri    6083672        29.0
16           Mississippi    2992333        28.0
17         Massachusetts    6794422        25.0
18             Minnesota    5489594        27.0
19              Michigan    9922576        26.0
20                 Maine    1329328        23.0
21              Maryland    6006401        24.0
22             Louisiana    4670724        22.0
23                Kansas    2911641        20.0
24                  Iowa    3123899        19.0
25              Kentucky    4425092        21.0
26          North Dakota     756927        38.0
27                Oregon    4028977        41.0
28              Oklahoma    3911338        40.0
29          Pennsylvania   12802503        42.0
30                  Ohio   11613423        39.0
31        North Carolina   10042802        37.0
32            New Mexico    2085109        35.0
33               Montana    1032949        30.0
34              New York   19795791        36.0
35                Nevada    2890845        32.0
36              Nebraska    1896190        31.0
37         New Hampshire    1330608        33.0
38            New Jersey    8958013        34.0
39                  Utah    2995919        49.0
40         West Virginia    1844128        54.0
41               Vermont     626042        50.0
42              Virginia    8382993        51.0
43             Wisconsin    5771337        55.0
44            Washington    7170351        53.0
45          Rhode Island    1056298        44.0
46        South Carolina    4896146        45.0
47             Tennessee    6600299        47.0
48                 Texas   27469114        48.0
49          South Dakota     858469        46.0
50               Wyoming     586107        56.0
51                   NaN    3474182        72.0